create table "public"."user table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "phone" boolean
);


alter table "public"."user table" enable row level security;

CREATE UNIQUE INDEX "user table_pkey" ON public."user table" USING btree (id);

alter table "public"."user table" add constraint "user table_pkey" PRIMARY KEY using index "user table_pkey";

grant delete on table "public"."user table" to "anon";

grant insert on table "public"."user table" to "anon";

grant references on table "public"."user table" to "anon";

grant select on table "public"."user table" to "anon";

grant trigger on table "public"."user table" to "anon";

grant truncate on table "public"."user table" to "anon";

grant update on table "public"."user table" to "anon";

grant delete on table "public"."user table" to "authenticated";

grant insert on table "public"."user table" to "authenticated";

grant references on table "public"."user table" to "authenticated";

grant select on table "public"."user table" to "authenticated";

grant trigger on table "public"."user table" to "authenticated";

grant truncate on table "public"."user table" to "authenticated";

grant update on table "public"."user table" to "authenticated";

grant delete on table "public"."user table" to "service_role";

grant insert on table "public"."user table" to "service_role";

grant references on table "public"."user table" to "service_role";

grant select on table "public"."user table" to "service_role";

grant trigger on table "public"."user table" to "service_role";

grant truncate on table "public"."user table" to "service_role";

grant update on table "public"."user table" to "service_role";


